### PR TITLE
Reticulum binding registration

### PR DESCRIPTION
**Pull request by brianpeiris**
- Split `bind` command into `bridge` and `create`
- Binding is only registered with reticulum with the `create` command.

### CODE REVIEW

**Comment by gfodor** [comment]
from discussion, lets drop `bridge` command and topic watching for hubs URLs, and focus on `create` being the exclusive way to introduce bindings/bridging

**Comment by gfodor** [comment]
we'll also need to have a command to unbridge/unbind/remove room from the topic -- probably `destroy`?

**Comment by gfodor** [comment]
as part of that I suppose we could also shut down the room, but not sure

**Comment by brianpeiris** [comment]
Removed the `bridge` command. Renamed `unbridge` command to `remove` -- it still only removes the url from the topic, which stops the bridging. I think it makes sense to keep a hub open and permissions-bound even if you remove the bridging

I was about to remove the topic scanning behavior as well, but I realized one downside is that the discord bot will not recover bridging if on restarts/redploys, since I believe we rely on the topic for that state.

**Comment by gfodor** [comment]
i guess we could ignore room URLs in topics that don't have a bridge registered in our db, but doesn't need to block

**Comment by mqp** [comment]
If we're going to say that being permission-bound === the bot should be bridging, and the source of truth for being permission-bound is Reticulum, then the bot should ask Reticulum on startup where to bridge.

**Comment by mqp** [comment]
I think we should have one of these:

1. Creating a room with the Discord bot, having a room be permission-bound, and having a room be bridged by the bot (while the bot is operational), are all the same thing. You will never have one without the other.

2. All three are independent and you can enable or disable permission-binding and bridging independently for any hub, and the Discord bot is just another UI to create rooms that doesn't have any special capabilities.

I don't think it makes sense to have something in between those two, where you can "remove" a room, which disables the bridging, but not the permission binding, but then you can't "re-add" the bridging. That seems confusing and I see no benefit. If you can "remove" a room that was created by the bot, then it should remove the permission binding, cease bridging, and shut down the room; the opposite of "create".

**Comment by brianpeiris** [comment]
It seems very destructive to have the bot close a on "remove", especially if there is no way to undo it. 

Querying reticulum for re-bridging sounds like a good idea, but I'm not going to tackle it with this push.

**Comment by mqp** [comment]
In the world where we bind on creation-via-bot, why do we continue to want a bot access key? I am happy for anyone to be able to create a Discord-bound room through the API.

**Comment by gfodor** [comment]
it seems right that there needs to be some form of credentials for an API to effectively sudo over to the bot (which is basically what the bot key does right?) that doesn't mean the credentials need to be singular or private as they are now (eg one day perhaps we could generate per-server credentials) -- but i don't think "anyone can always sudo to the bot" is a safe model.

**Comment by brianpeiris** [comment]
Yes, the bot access key grants the ability to create bound hubs and join any bound hub, both of which ought to be gated by installing our discord bot, since that gives us control of the behavior against the API.

**Pull request merged**
